<?php

use HnhDigital\LaravelFrontendAssetPack as Assets;

return [
    'Animate'                 => [Assets\Animate::class, '3.5.2'],
    'Autosize'                => [Assets\Autosize::class, '4.0.0'],
    'Backbone'                => [Assets\Backbone::class, '1.3.3'],
    'BackboneMarionette'      => [Assets\BackboneMarionette::class, '3.5.0'],
    'BackboneLocalPersist'    => [Assets\BackboneLocalPersist::class, '1.1.1'],
    'Bootstrap'               => [Assets\Bootstrap::class, '4.0.0'],
    'ChartJs'                 => [Assets\ChartJs::class, '2.7.1'],
    'Clipboard'               => [Assets\Clipboard::class, '2.0.0'],
    'CodeMirror'              => [Assets\CodeMirror::class, '5.48.2'],
    'PasswordComplexifyInput' => [Assets\PasswordComplexifyInput::class, '0.5.1'],
    'DateInput'               => [Assets\DateInput::class, '1.8.0'],
    'DiffMatchPatch'          => [false, '20121119'],
    'Dropzone'                => [Assets\Dropzone::class, '5.4.0'],
    'ElementTransitions'      => [Assets\ElementTransitions::class],
    'FontAwesome'             => [Assets\FontAwesome::class, '5.4.1'],
    'FlagIcon'                => [Assets\FlagIcon::class],
    'Flot'                    => [Assets\Flot::class, '0.8.3'],
    'FlotTooltop'             => [Assets\FlotTooltop::class, '0.8.7'],
    'GoogleMaps'              => [
        'class'   => Assets\GoogleMaps::class,
        'plugins' => [
            'MarkerClusterer' => '1.0.0',
        ],
    ],
    'GoogleAnalytics'         => [Assets\GoogleAnalytics::class],
    'GoogleRecaptcha'         => [Assets\GoogleRecaptcha::class],
    'Highlight'               => [Assets\Highlight::class, '9.15.9'],
    'IcheckInput'             => [Assets\IcheckInput::class, '1.0.2'],
    'IfVisibleJs'             => [Assets\IfVisibleJs::class, '1.0.6'],
    'Jquery'                  => [
        'class'     => Assets\Jquery::class,
        'version'   => '3.4.1',
        'integrity' => 'sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=',
    ],
    'JqueryUi'                => [
        'class'     => Assets\JqueryUi::class,
        'version'   => '1.12.1',
        'integrity' => [
            'jquery-ui.min.js'             => 'sha256-KM512VNnjElC30ehFwehXjx1YCHPiQkOPmqnrWtpccM=',
            'smoothness-jquery-ui.min.css' => 'sha256-vpKTO4Ob1M4bZ8RAvZvYMtinMz1XjH0QYdAO2861V9M=',
        ],
        'theme' => 'smoothness',
    ],
    'Ladda'                   => [Assets\Ladda::class, '1.0.0'],
    'MarkdownIt'              => [Assets\MarkdownIt::class, '8.4.2'],
    'MetisMenu'               => [Assets\MetisMenu::class, '2.5.2'],
    'MiniColors'              => [Assets\MiniColors::class, '2.2.6'],
    'MultiEmailInput'         => [Assets\MultiEmailInput::class, '0.0.2'],
    'Pace'                    => [Assets\Pace::class, '1.0.2'],
    'Popper'                  => [Assets\Popper::class, '1.15.0'],
    'Raphael'                 => [Assets\Raphael::class, '2.2.8'],
    'Redactor'                => [Assets\Redactor::class],
    'SignaturePad'            => [Assets\SignaturePad::class, '2.3.2'],
    'Slimscroll'              => [Assets\Slimscroll::class, '1.3.7'],
    'Sparkline'               => [Assets\Sparkline::class, '2.1.2'],
    'TextDiff'                => [Assets\TextDiff::class, '1.0.4'],
    'Toastr'                  => [Assets\Toastr::class, '2.1.4'],
    'Select2'                 => [Assets\Select2::class, '4.0.5'],
    'Slick'                   => [Assets\Slick::class, '1.8.1'],
    'Steps'                   => [Assets\Steps::class, '1.1.0'],
    'StickyTabs'              => [Assets\StickyTabs::class, '1.0.3'],
    'Stripe'                  => [Assets\Stripe::class, '3'],
    'SquireRte'               => [Assets\SquireRte::class, '1.9.0'],
    'ToMark'                  => [Assets\ToMark::class, '1.1.6'],
    'Tooltip'                 => [Assets\Tooltip::class, '1.3.2'],
    'TagsInput'               => [Assets\TagsInput::class, '0.8.0'],
    'TimeInput'               => [Assets\TimeInput::class, '1.11.13'],
    'Translations'            => [Assets\Translations::class],
    'TuiEditor'               => [
        'class'   => Assets\TuiEditor::class,
        'version' => '1.2.5',
        'plugins' => [
            'CodeSnippet' => '1.3.0',
            'ColorPicker' => '2.2.0',
        ],
    ],
    'Underscore'              => [Assets\Underscore::class, '1.8.3'],
    'ValidateInput'           => [Assets\ValidateInput::class, '1.15.0'],
    'Vectormap'               => [Assets\Vectormap::class, '2.0.2'],
    'VideoJs'                 => [Assets\VideoJs::class, '6.4.0'],
    'Vue'                  => [
        'class'     => Assets\Vue::class,
        'version'   => '2.6.10',
        'integrity' => 'sha256-chlNFSVx3TdcQ2Xlw7SvnbLAavAQLO0Y/LBiWX04viY=',
    ],
    'VueRouter'                  => [
        'class'     => Assets\VueRouter::class,
        'version'   => '3.0.7',
        'integrity' => 'sha256-6tMH70lVyWtoEQCEGNDnofD+Tg1iqdBm0uXvK2Q9zlk=',
    ],
    'Zip'                     => [Assets\Zip::class, '2.6.1'],
];
